# Run
run_name: sdss_14  # Run name
num_gpus: 1  # Number of gpus to use
compile_on: gpu  # Compile model on 'cpu' or 'gpu'

# Data
path_data:  # If None, automatically search for the data
dataset: sdss_debug  # Name of the data set
image_shape: (16, 16)  # Image shape (height, width)
bands: u, g, r, i, z  # Bands to use
num_class: 180  # Number of classes for the classification
frac_train: 0.8  # fraction of data in training set (remaind in test set)
random_state: 200  # random seed

# Model
model_name: sdss  # Name of the model
routings: 3  # Number of routing steps for the dynamic routing algorithm
dim_capsule: 8  # Dimension of the vector space for each capsule
batch_size: 32  # Batch size for the data ingestion

# Training
epochs: 25  # Number of epochs to run the training
checkpoint:  # Epoch at which to start training. Use None if starting fresh.
learning_rate: 0.001  # Initial learning rate
decay_rate: 0.9  # Decay rate of the learning rate
lam_recon: 0.0005  # penalty for the sum of square error for the regulariser decoder

# Output
timeline: False  # create a TF Timeline
path_results: "."  # Output path
